### ISSUE TITLE
[Server/Client] Test server with new client networking

### ISSUE THREAD

**Issue by Videntory** [jewelsz/Tank-war-Proftaak#18]
Requires #19 to be solved.
The server is currently being tested with the old version of the client networking that was not able to be implemented due to difficulties with Unity.
Right now we switched to a client side networking library specifically made for Unity. 
For more information refer to: #1

**Comment by metalglove** [comment]
We switched back to the old networking code. It seems to work now. This issue will be closed, and only reopened if the networking seems to stop working...
